ID_DV <- read.csv("~/Downloads/AMS 315 F22 - Project 1 Part A Data Files (1)/941886_DV.csv")
View(ID_DV)
ID_IV <- read.csv("~/Downloads/AMS 315 F22 - Project 1 Part A Data Files (1)/941886_IV.csv")
View(ID_IV)
ID_IV_DV <- merge(ID_DV, ID_IV, by = "ID")
ID_IV_DV
View(ID_IV_DV)
nrow(ID_IV_DV)
length(ID_IV_DV[ID_IV_DV$DV > 0])
length(ID_IV_DV[ID_IV_DV$DV > 0,])
ID_IV_DV[ID_IV_DV$DV > 0]
ID_IV_DV[ID_IV_DV$DV > 0,]
length(ID_IV_DV[,ID_IV_DV$DV > 0])
length(ID_IV_DV[ID_IV_DV$DV > 0, ID_IV_DV$IV > 0 ])
length(ID_IV_DV[, ID_IV_DV$DV > 0, ID_IV_DV$IV > 0 ])
length(ID_IV_DV)
length(ID_IV_DV$DV)
length(ID_IV_DV$DV > 0)
length(ID_IV_DV$DV, na.rm = TRUE)
install.packages("dplyr")
str(ID_IV_DV)
table(ID_IV_DV['DV'])
length(ID_IV_DV$DV[!is.na(ID_IV_DV$DV)])
length(ID_IV_DV$IV[!is.na(ID_IV_DV$IV)])
length(ID_IV_DV$DV[!is.na(ID_IV_DV$DV)] & ID_IV_DV$IV[!is.na(ID_IV_DV$IV)])
length(ID_IV_DV[!is.na(ID_IV_DV)])
sum(is.na(ID_IV_DV$DV))
sum(is.na(ID_IV_DV$DV) & is.na(ID_IV_DV$IV))
sum(ID_IV_DV$DV[!is.na(ID_IV_DV$DV)] & ID_IV_DV$IV[!is.na(ID_IV_DV$IV)])
length(ID_IV_DV[ID_IV_DV$DV > 0 & ID_IV_DV$IV > 0, ])
ID_IV_DV[ID_IV_DV$DV > 0 & ID_IV_DV$IV > 0, ]
sum(!is.na(ID_IV_DV$DV) & !is.na(ID_IV_DV$IV))
sum(!is.na(ID_IV_DV$DV) & is.na(ID_IV_DV$IV))
length(!is.na(ID_IV_DV$DV) & is.na(ID_IV_DV$IV))
sum(is.na(ID_IV_DV$DV) & !is.na(ID_IV_DV$IV))
sum(is.na(ID_IV_DV$DV) & !is.na(ID_IV_DV$IV))
install.packages("mice")
library(mice)
sum(is.na(ID_IV_DV$DV) & !is.na(ID_IV_DV$IV))
sum(!is.na(ID_IV_DV$DV) & is.na(ID_IV_DV$IV))
sum(!is.na(ID_IV_DV$DV) & !is.na(ID_IV_DV$IV))
sum(is.na(ID_IV_DV$DV) & is.na(ID_IV_DV$IV))
PartA_imp <- ID_IV_DV[!is.na(ID_IV_DV$IV) == TRUE | !is.na(ID_IV_DV$DV) == TRUE,]
imp <- mice(PartA_imp, method = "norm.boot", printFlag = FALSE)
PartA <- complete(imp)
md.pattern(PartA)
View(PartA)
lm(DV ~ IV, data = PartA)
summary(lm(DV ~ IV, data = PartA))
anova(lm(DV ~ IV, data = PartA))
plot(PartA$DV ~ PartA$IV, main = 'Scatter: DV ~ IV', xlab = 'IV', ylab = 'DV', pch = 20, lty = 3, lwd = 2)
abline(lm(DV ~ IV, data = PartA), col = 'red', lty = 'dashed', lwd = 5)
legend('topleft', legend='Estimated Regression Line', lty=3, lwd=2, col='red')
confint(lm(DV ~ IV, data = PartA), level = 0.95)
confint(lm(DV ~ IV, data = PartA), level = 0.99)
PartB <- read.csv("~/Downloads/AMS 315 F22 - Project 1 Part B Data Files (1)/941886_PartB.csv")
View(PartB)
plot(PartB$y ~ PartB$x)
sqrt_y <- sqrt(PartB$y)
plot(sqrt_y ~ PartB$x)
inv_y <- 1/(PartB$y)
plot(inv_y ~ PartB$x)
ln_y <- ln(PartB$y)
ln_y <- log(PartB$y)
plot(ln_y ~ PartB$x)
plot(PartB$y ~ PartB$x)
plot(ln_y ~ PartB$x)
plot(inv_y ~ PartB$x)
summary(PartB$x)
bin_x <- cut(PartB$x, breaks = 15)
plot(PartB$y ~ bin_x)
plot(inv_y ~ bin_x)
plot(sqrt_y ~ bin_x)
cut_x <- cut(PartB$x, breaks = seq(5, 20, by = 1))
plot(PartB$y ~ cut_x)
plot(inv_y, cut_x)
plot(inv_y ~ cut_x)
ave(cut_x)
ave(x, FUN = mean)
ave(cut_x, FUN = mean)
table(cut_x)
new_x <- ave(PartB$x, cut_x)
new_x
plot(PartB$y, new_x)
plot(PartB$y ~ new_x)
data_trans <- data.frame(xtrans = PartB$x, ytrans = 1/(PartB$y))
groups <- cut(PartB$x ,breaks=c(-Inf,seq(min(PartB$x)+0.3, max(PartB$x)-0.3,by=0.3),Inf))
table(groups)
x <- ave(PartB$x, groups)
data_bin <- data.frame(x = x, y = data_trans$ytrans)
plot(data_trans$ytrans ~ x)
